spring:
  data:
    mongodb:
      uri: mongodb+srv://root:root@bookfreak.tcd27.mongodb.net/
      database: users_db
  application:
    name: auth-module
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: ff4cbc0b7b5f17
    password: 9c604a35bfda06
    protocol: smtp
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 8443
  ssl:
    key-store: classpath:https-springboot.jks
    key-store-password: password
    key-store-type: JKS
    key-alias: https-springboot
    key-password: password

app:
  security:
    secretKey: 942P43hf2bnfrepqaskJfsj09fq2JFdeEKAFDMKmfl2FD
    expirationTime: 600

eureka:
  client:
    fetch-registry: true
    register-with-eureka: false
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

zuul:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  host:
    connect-timeout-millis: 600000
    socket-timeout-millis: 600000
#  ignored-services: '*'
#  prefix: /api/v1
  routes:
    author-module:
      url: http://localhost:8081
#      path: /api/v1/authors/**
#      service-id: author-module
    book-module:
      url: http://localhost:8082
#      path: /books/**
#      service-id: book-module
    user-module:
      url: http://localhost:8083
#      path: /users/**
#      service-id: user-module

management:
  endpoints:
    web:
      exposure:
        include: '*'

springdoc:
  swagger-ui:
    path: "/v3/api-docs/index.html"
    disable-swagger-default-url: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 150000

ribbon:
  ConnectTimeout: 6000
  ReadTimeout: 6000
  eureka:
    enabled: true

logging:
  level:
    web: TRACE
    org.springframework:
      web: TRACE