spring:
  data:
    mongodb:
      uri: mongodb+srv://root:root@bookfreak.tcd27.mongodb.net/
      database: users_db
  application:
    name: user-module

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    instance-id: user-module

server:
  port: 8083