server:
  port: 8761

spring:
  application:
    name: eureka-module

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: https://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost